import type { Metadata } from "next";
import { Toaster } from "sonner";
import QueryProviders from "@/providers/query-provider";
import { Varela } from "next/font/google";
import "./globals.css";

const varela = Varela({
  subsets: ["latin"],
  variable: "--font-varela-logo",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Cliveworks",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={`${varela.variable}`}>
      <body className="min-h-screen min-w-[1400px] bg-background antialiased">
        <QueryProviders>
          <div className="relative flex min-h-screen flex-col bg-background">
            {children}
          </div>
        </QueryProviders>
        <Toaster position="top-center" duration={3000} />
      </body>
    </html>
  );
}
